on: [push, pull_request]
name: Test
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.x'
      - name: Download dependencies
        run: go mod download
      - name: Run tests
        run: go run gotest.tools/gotestsum@latest --junitfile reports/tests.xml
      - name: Test Report
        uses: dorny/test-reporter@v1
        if: success() || failure()
        with:
          name: Tests report
          path: reports/*.xml
          reporter: jest-junit
